version: "3.3"

services:
  microservicecicd-send-email:
    image: microservice-microservicecicd-send-email:v1
    ports:
      - 8081:8081
    environment:
      - spring.boot.admin.client.url=${SPRING_ADMIN}
    networks:
      - microservice

networks:
  microservice:
    external: true