version: "3.3"

services:
  microservicecicd-send-sms:
    image: microservice-microservicecicd-send-sms:v1
    ports:
      - 8082:8082
    environment:
      - spring.boot.admin.client.url=${SPRING_ADMIN}
    networks:
      - microservice

networks:
  microservice:
    external: true